defaults:
  - model: linear_logreg

data_path: "data/samples/agarwal-aneja_15_15_B20_Theta0.2_BF1.0"
num_samples: null
var_size_samples: False
train_batch_size: 32
val_batch_size: 128
max_num_epochs: 500
learning_rate: 0.001
momentum: 0.9
weight_decay: 0
lr_decay: True
patience: 5
lr_decay_factor: 0.1
early_stopping: 15
opt_threshold: 0.00001
monitoring_kpi: "validation_loss"
# out_dir: "models/sol_edge_predictor"
##Changes
out_dir: "models/sol_arc_predictor"
top_k : 200
regul_lambda : 0.1
max_iterations_FW : 15
alpha : 10
beta : 1
##End changes
log_dir: "logs"
use_gpu: False
seed: 0
cross_validate: False
test_split: 0.2
##changes
# Lazy loading toggle (memory-saving dataset)
lazy_loading: False
#end changes

# =====================
# Problem definition
# =====================
problem:
  type: cvrp        # [cvrp | cvrptw]

  time_windows:
    enabled: false  # problem.type == cvrptw ise otomatik true yapılabilir
    horizon: 1000.0
    width_min: 150.0
    width_max: 300.0
    service_time: 0.0
    seed: 0

# =====================
# Sample generation
# =====================
sampling:
  timelimit: 60
  outputflag: 0
  nb_clients: 20
  vehicle_capacity: 30
  nb_vehicles: 5

paths:
  out_dir:   "data/samples_Munich"

# =====================
# Hydra behavior (IMPORTANT)
# =====================
hydra:
  run:
    dir: .
  output_subdir: null
